feature-modal
Bhakti199/Ranger-UI pull request #11
Opened 2022-02-07 18:34 UTC by Bhakti199

here I added standard modal.

2022-02-07 19:07 UTC, munjalSaksham71 approved these changes

2022-02-07 19:16 UTC, shaksham08 approved these changes

2022-02-07 19:17 UTC, shaksham08 approved these changes
Looks Good

2022-02-07 19:19 UTC, tusharkandpal requested changes

2022-02-07 19:19 UTC, tusharkandpal commented on modal/modal.css
> +  width: 37rem;
Giving fix values may cause problem in responsive design of your library

2022-02-07 19:19 UTC, tusharkandpal commented on modal/modal.css
> +  margin-top: 2rem;
Can combine these two lines in one. `margin: 2rem 0;`

2022-02-07 19:19 UTC, tusharkandpal commented on modal/modal.html
> +        ><a href="" class="ranger-ui ranger-ui-name">RangerUI</a></span
`href` attribute is empty

2022-02-08 05:09 UTC, tusharkandpal approved these changes
Looks good to merge now. Great work with library! 👍🙂

2022-02-08 05:26 UTC, merged